### ISSUE TITLE
Bitbucket cloud errors out on webhook - NPE on repository owner.getUsername()

### ISSUE THREAD

**Issue by benjaminstokes** [checkmarx-ts/cx-flow#6]
A Null Pointer Exception is thrown when using CxFlow with Bitbucket Cloud. 

```
2019-09-03 06:36:52.074  INFO 11632 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService
2019-09-03 06:36:52.074  INFO 11632 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService 'webHook'
2019-09-03 06:36:52.777  INFO 11632 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping     [] : Adding welcome page template: index
2019-09-03 06:36:53.246  INFO 11632 --- [           main] o.s.b.a.e.w.EndpointLinksResolver         [] : Exposing 2 endpoint(s) beneath base path '/actuator'
2019-09-03 06:36:53.308  INFO 11632 --- [           main] o.s.b.w.e.t.TomcatWebServer               [] : Tomcat started on port(s): 8081 (http) with context path ''
2019-09-03 06:36:53.308  INFO 11632 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 7.369 seconds (JVM running for 7.851)
2019-09-03 06:37:04.558  INFO 11632 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/]                         [] : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-09-03 06:37:04.558  INFO 11632 --- [nio-8081-exec-1] o.s.w.s.DispatcherServlet                 [] : Initializing Servlet 'dispatcherServlet'
2019-09-03 06:37:04.574  INFO 11632 --- [nio-8081-exec-1] o.s.w.s.DispatcherServlet                 [] : Completed initialization in 16 ms
2019-09-03 06:37:04.716  INFO 11632 --- [nio-8081-exec-1] c.c.f.c.BitbucketCloudController          [MpwJDhQb] : Validating BitBucket request token
2019-09-03 06:37:04.716  INFO 11632 --- [nio-8081-exec-1] c.c.f.c.BitbucketCloudController          [MpwJDhQb] : Validation successful
2019-09-03 06:37:04.731 ERROR 11632 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]       [MpwJDhQb] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing
failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at com.checkmarx.flow.controller.BitbucketCloudController.pushRequest(BitbucketCloudController.java:288) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_221]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at com.checkmarx.flow.filter.SecurityFilter.doFilter(SecurityFilter.java:41) ~[classes!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_221]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_221]

```

The NPE occurs because the repository owner field is null. username is not sent by bitbucket in the webhook.

Sample payload:
```
{
  "pullrequest": {
    "rendered": {
      "description": {
        "raw": "testing cxflow",
        "markup": "markdown",
        "html": "<p>testing cxflow</p>",
        "type": "rendered"
      },
      "title": {
        "raw": "server.js edited online with Bitbucket",
        "markup": "markdown",
        "html": "<p>server.js edited online with Bitbucket</p>",
        "type": "rendered"
      }
    },
    "type": "pullrequest",
    "description": "testing cxflow",
    "links": {
      "decline": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/decline"
      },
      "diffstat": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/diffstat/stokesbo/dvna-clone:c8db3fbcd5d7%0Dc637437d6515?from_pullrequest_id=1"
      },
      "commits": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/commits"
      },
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1"
      },
      "comments": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/comments"
      },
      "merge": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/merge"
      },
      "html": {
        "href": "https://bitbucket.org/stokesbo/dvna-clone/pull-requests/1"
      },
      "activity": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/activity"
      },
      "diff": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/diff/stokesbo/dvna-clone:c8db3fbcd5d7%0Dc637437d6515?from_pullrequest_id=1"
      },
      "approve": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/approve"
      },
      "statuses": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/pullrequests/1/statuses"
      }
    },
    "title": "server.js edited online with Bitbucket",
    "close_source_branch": false,
    "reviewers": [],
    "id": 1,
    "destination": {
      "commit": {
        "hash": "c637437d6515",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/commit/c637437d6515"
          },
          "html": {
            "href": "https://bitbucket.org/stokesbo/dvna-clone/commits/c637437d6515"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone"
          },
          "html": {
            "href": "https://bitbucket.org/stokesbo/dvna-clone"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B6fbba6cc-d99d-4f8d-8d9e-334442551a5f%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "dvna-clone",
        "full_name": "stokesbo/dvna-clone",
        "uuid": "{6fbba6cc-d99d-4f8d-8d9e-334442551a5f}"
      },
      "branch": {
        "name": "master"
      }
    },
    "created_on": "2019-09-03T06:13:04.318109+00:00",
    "summary": {
      "raw": "testing cxflow",
      "markup": "markdown",
      "html": "<p>testing cxflow</p>",
      "type": "rendered"
    },
    "source": {
      "commit": {
        "hash": "c8db3fbcd5d7",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone/commit/c8db3fbcd5d7"
          },
          "html": {
            "href": "https://bitbucket.org/stokesbo/dvna-clone/commits/c8db3fbcd5d7"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone"
          },
          "html": {
            "href": "https://bitbucket.org/stokesbo/dvna-clone"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B6fbba6cc-d99d-4f8d-8d9e-334442551a5f%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "dvna-clone",
        "full_name": "stokesbo/dvna-clone",
        "uuid": "{6fbba6cc-d99d-4f8d-8d9e-334442551a5f}"
      },
      "branch": {
        "name": "cflow-testing"
      }
    },
    "comment_count": 0,
    "state": "OPEN",
    "task_count": 0,
    "participants": [],
    "reason": "",
    "updated_on": "2019-09-03T06:13:04.356122+00:00",
    "author": {
      "display_name": "Ben Stokes",
      "account_id": "5bf09f59d4a331274030494c",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D/"
        },
        "avatar": {
          "href": "https://secure.gravatar.com/avatar/035b85a04c1eed04b3575e27771080bb?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FBS-4.png"
        }
      },
      "nickname": "Ben Stokes",
      "type": "user",
      "uuid": "{a99a2fe3-8377-46ed-9471-956c8f96493b}"
    },
    "merge_commit": null,
    "closed_by": null
  },
  "repository": {
    "scm": "git",
    "website": "",
    "name": "dvna-clone",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/stokesbo/dvna-clone"
      },
      "html": {
        "href": "https://bitbucket.org/stokesbo/dvna-clone"
      },
      "avatar": {
        "href": "https://bytebucket.org/ravatar/%7B6fbba6cc-d99d-4f8d-8d9e-334442551a5f%7D?ts=default"
      }
    },
    "full_name": "stokesbo/dvna-clone",
    "owner": {
      "display_name": "Ben Stokes",
      "account_id": "5bf09f59d4a331274030494c",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D/"
        },
        "avatar": {
          "href": "https://secure.gravatar.com/avatar/035b85a04c1eed04b3575e27771080bb?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FBS-4.png"
        }
      },
      "nickname": "Ben Stokes",
      "type": "user",
      "uuid": "{a99a2fe3-8377-46ed-9471-956c8f96493b}"
    },
    "type": "repository",
    "is_private": false,
    "uuid": "{6fbba6cc-d99d-4f8d-8d9e-334442551a5f}"
  },
  "actor": {
    "display_name": "Ben Stokes",
    "account_id": "5bf09f59d4a331274030494c",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D"
      },
      "html": {
        "href": "https://bitbucket.org/%7Ba99a2fe3-8377-46ed-9471-956c8f96493b%7D/"
      },
      "avatar": {
        "href": "https://secure.gravatar.com/avatar/035b85a04c1eed04b3575e27771080bb?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FBS-4.png"
      }
    },
    "nickname": "Ben Stokes",
    "type": "user",
    "uuid": "{a99a2fe3-8377-46ed-9471-956c8f96493b}"
  }
}

```

The NPE occurs at owner.getUsername to create a scanRequest.Namespace at these locations:
* https://github.com/checkmarx-ts/cx-flow/blob/master/src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java#L144
* https://github.com/checkmarx-ts/cx-flow/blob/master/src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java#L288

**Comment by benjaminstokes** [comment]
Fixed by https://github.com/checkmarx-ts/cx-flow/pull/7
